import type { ReactNode } from "react";
import { PageShell, DISCORD_URL } from "./PageShell";

export function BlankPage() { return <PageShell eyebrow="Mocha / page" title="Nothing here yet." intro="This route exists, but it has not been given a page body."><a className="site-back-link" href="/">← back home</a></PageShell>; }
export function ZephyrPage() { return <BlankPage />; }

export function PremiumPage() { return <PageShell eyebrow="Product / premium" title="Premium, without the dashboard." intro="A dedicated home for the paid Mocha experience."><div className="feature-grid"><div className="feature-panel"><span>01</span><h2>More control</h2><p>Put premium-only controls and server upgrades here without mixing them into the docs.</p></div><div className="feature-panel"><span>02</span><h2>Same workflow</h2><p>Premium stays in-chat first, keeping the product consistent with the rest of Mocha.</p></div><div className="feature-panel"><span>03</span><h2>Upgrade path</h2><p>Add your final pricing, checkout, and plan comparison here when those details are ready.</p></div></div></PageShell>; }

const COMMANDS = [["call","Connect this channel to another server, or join the queue to get matched."],["hangup","End the current call, or leave the queue."],["ban / kick","Remove a member, with a reason attached to the log."],["mute / unmute","Timeout a member for a set number of minutes."],["lock / unlock","Stop or restore everyone's ability to send messages in a channel."],["/set-prefix","Change the command prefix for your server."],["help","Open the full command index."]];
export function CommandsPage() { return <PageShell eyebrow="Product / commands" title="Commands." intro="The standalone command browser for people who want the list without opening the full documentation."><div className="command-directory">{COMMANDS.map(([name, description]) => <div className="command-row" key={name}><code>{name}</code><p>{description}</p></div>)}</div></PageShell>; }

export function HelpPage() { return <PageShell eyebrow="Support / get help" title="Need a hand?" intro="Bug reports, setup questions, updates, and direct support live in the official Mocha server."><div className="help-panel"><div><span className="help-kicker">Official support</span><h2>Come hang out where Mocha actually lives.</h2><p>Join the support server for troubleshooting, suggestions, bug reports, and product updates.</p></div><a className="btn-sticker" href={DISCORD_URL} target="_blank" rel="noreferrer"><span className="shard" /><span className="plate">Join Discord →</span></a></div></PageShell>; }

function LegalPage({ title, eyebrow, intro, children }: { title: string; eyebrow: string; intro: string; children: ReactNode }) { return <PageShell eyebrow={eyebrow} title={title} intro={intro}><article className="legal-article">{children}</article></PageShell>; }
export function TermsPage() { return <LegalPage eyebrow="Legal / terms" title="Terms of Service" intro="The rules for using Mocha and its website."><h2>Using the service</h2><p>By using Mocha, you agree to follow Discord's rules, applicable law, and any server-level rules set by your community.</p><h2>Availability</h2><p>Mocha may change, pause, or remove features as the service evolves. Availability is not guaranteed unless your final terms say otherwise.</p><h2>Acceptable use</h2><p>Do not use Mocha to abuse, harass, disrupt, or unlawfully access other users, servers, or systems.</p></LegalPage>; }
export function PrivacyPage() { return <LegalPage eyebrow="Legal / privacy" title="Privacy Policy" intro="A clear place to explain what information Mocha processes and why."><h2>Information processed</h2><p>Specify here what Discord identifiers, server settings, command information, logs, analytics, or support messages your service stores.</p><h2>How it is used</h2><p>Describe the operational reasons for collection, such as providing bot functionality, moderation logs, support, security, and service improvements.</p><h2>Retention and deletion</h2><p>State your retention periods and explain how a server owner or user can request deletion where applicable.</p></LegalPage>; }
export function RefundsPage() { return <LegalPage eyebrow="Legal / refunds" title="Refunds" intro="The policy page for premium purchases, cancellations, and refund requests."><h2>Refund window</h2><p>Insert your actual refund eligibility period and the conditions under which a purchase may be refunded.</p><h2>Cancellations</h2><p>Explain what happens to premium access when a subscription is canceled and when that access ends.</p><h2>How to contact support</h2><p>Direct refund requests to the official support server or the payment channel you actually use.</p><a className="site-back-link" href="/help">refund help →</a></LegalPage>; }
